---
:now:
- :mindless_browsing_more_than_30_minutes
- :more_than_2_double_cofes
- :oversleeping_more_than_9_hours
- :overeating_did_i_feel_too_stuffed_at_some_point
- :sweets_it_s_ok_on_cheatdays
- :soft_drinks_it_s_ok_on_cheatdays
- :alcohol_it_s_ok_on_cheatdays
- :more_than_8_hours_in_the_office
- :more_than_20_minutes_of_xbox
- :exercise_commute_by_bike_or_smth_else
- :diet_primal_low_carb_paleo
- :writing_30_minutes_in_front_of_monitor
- :wakeup_8am
:later:
- :morning_routine
- :gtd_did_you_follow_it
- :6_hours_of_sleep
- :updated_tumblr_within_last_3_days
- :wrote_to_called_meet_someone_i_care_about_proactively
- :did_i_spend_on_impulse
- :did_i_drink_more_than_1_5_liters_of_mineral_water
- :was_i_in_the_flow_today